name: Makefile CI

env:
  RUST_BACKTRACE: 1
  PROJECT_DIR: xks-axum

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  style:
    name: Check Style
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Check format
        run: cargo fmt --manifest-path=${{ env.PROJECT_DIR }}/Cargo.toml --all -- --check

  test-n-clippy:
    name: Unit Test and Clippy
    needs: style
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-22.04
#          - al2
#          - al2aarch64

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust Stable
      uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy

    - name: Unit Test
      run: cargo test --manifest-path=${{ env.PROJECT_DIR }}/Cargo.toml

    - name: Clippy
      run: cargo clippy --manifest-path=${{ env.PROJECT_DIR }}/Cargo.toml

  miri:
    name: Check for Undefined Behavior
    needs: style
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-22.04
#          - al2
#          - al2aarch64

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust Nightly
      uses: dtolnay/rust-toolchain@nightly
      with:
        components: miri

    - name: Miri Test
      env:
        MIRIFLAGS: -Zmiri-disable-isolation
      run: cargo +nightly miri test --manifest-path=${{ env.PROJECT_DIR }}/Cargo.toml

  check-on-macos:
    name: Check on Mac
    needs: style
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Check
      run: cargo check --manifest-path=${{ env.PROJECT_DIR }}/Cargo.toml
